### ISSUE TITLE
Deleting existing non-`linux-firmware` firmware (`rsync --delete`) could mess everything up

### ISSUE THREAD

**Issue by Rongronggg9** [q3aql/drivers-linux-firmware#4]
https://github.com/q3aql/drivers-linux-firmware/blob/6bea70dc11905758c3724a9ea60b7bc3dbe4b62f/usr/bin/drivers-linux-firmware#L33

The package itself contains only firmware from `linux-firmware` but not all files already located in `/lib/firmware` are from `linux-firmware` (e.g. `firmware-sof-signed`). Thus, `--delete` effectively deletes all non-`linux-firmware` firmware, potentially messing everything up. This behavior does not finish the goal of "not to conflict with other packages".

Also, I am confused, why `rsync` was chosen to sync firmware instead of a symlink farm? 🤔

```console
> apt show firmware-sof-signed
Package: firmware-sof-signed
Version: 2.1.1-1
Priority: optional
Section: non-free/kernel
Source: firmware-sof
Maintainer: Mark Pearson <markpearson@lenovo.com>
Installed-Size: 14.9 MB
Homepage: https://github.com/thesofproject/sof-bin
Download-Size: 787 kB
APT-Manual-Installed: yes
APT-Sources: https://mirrors.bfsu.edu.cn/debian testing/non-free amd64 Packages
Description: Intel SOF firmware - signed
 Provides the Intel SOF audio firmware and topology needed for audio
 functionality on some Intel system.
 .
 This package contains the pre-built and signed binaries.
```

**Comment by q3aql** [comment]
When you use symbolic links, if the files are named the same as another package, it conflicts and cannot be installed (that is the conflict you are referring to). For that reason, you cannot use symbolic links.

If you add any extra firmware, you must copy it to "/opt/drivers-linux-firmware/" as indicated in the README. You also don't have to use this package if you don't want to. You can simply download the linux-firmware files yourself, put them in manually and check that they are not overwritten with a system update 😉 😘

**Comment by Rongronggg9** [comment]
Thanks for your effort.

Still, I think solving the **installation** problem by using a `postinst` to override all existing firmware later is more like "acting as an ostrich that buries its head in the sand" rather than "not to conflict with other packages".

If you have to remove all existing firmware, writing `Conflicts` in the `control` file at least let users know "oh, my existing firmware will be gone!" But current behavior just doing this silently, without any warning or informing. `README` said, "If you want to **add new** modules, firmwares or drivers, they should ...", but please, **my existing firmware is not something new to add**! It also said, "all files will be synced to the `/lib/firmware/` directory", "syncing files" does not equal "syncing their parent folder", right? Thus, even after reading the `README` carefully, one can hardly understand the fact that their existing non-conflict firmware will be gone after installing those packages from this repo.

[Searching for source packages of non-free firmware in the Debian Bullseye repository](https://packages.debian.org/search?keywords=firmware&searchon=sourcenames&suite=stable&section=non-free), you will get 8 results, in which one is `firmware-nonfree` (`linux-firmware`). The remaining 7 source packages, which are non-`linux-firmware`, build 8 binary packages. That is to say, at least those firmware from the 8 packages will be unnecessarily deleted by your package. The reason why I use `firmware-sof-signed` as an example is that almost all recent notebooks with Intel processors and digital microphones need it to make their sound cards fully work (ref: https://thesofproject.github.io/latest/getting_started/intel_debug/introduction.html).

I am not complaining about this project and of course I know how to use the upstream repository. But I sincerely suggest you, to be more responsible, either not delete existing non-conflict firmware (still I don't understand why deleting them is a must), or give users enough warning both in the `README` and `preinst`.
